pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        maven {
            name = "Paper"
            url = "https://repo.papermc.io/repository/maven-public/"
        }
    }
}

rootProject.name = "minecraft-naked-and-afraid"
include("paper-plugin")
