pluginManagement {
    repositories {
        maven {
            name = "Fabric"
            url = "https://maven.fabricmc.net/"
        }
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        maven {
            name = "Fabric"
            url = "https://maven.fabricmc.net/"
        }
        maven {
            name = "Paper"
            url = "https://repo.papermc.io/repository/maven-public/"
        }
    }
}

rootProject.name = "minecraft-server-control"
include("fabric-client", "paper-plugin")
