plugins {
    id "java-library"
}

base {
    archivesName = "nakedandafraid-paper"
}

dependencies {
    compileOnly "io.papermc.paper:paper-api:${project.paper_api_version}"
    implementation "org.bstats:bstats-bukkit:3.1.0"
}

processResources {
    inputs.property "version", project.version

    filesMatching("plugin.yml") {
        expand(version: project.version)
    }
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from {
        configurations.runtimeClasspath.collect { dependency ->
            dependency.isDirectory() ? dependency : zipTree(dependency)
        }
    }
}
