plugins {
    id "java-library"
    id "com.gradleup.shadow" version "9.2.2"
}

base {
    archivesName = "nakedandafraid-paper"
}

dependencies {
    compileOnly "io.papermc.paper:paper-api:${project.paper_api_version}"
    implementation "org.bstats:bstats-bukkit:3.1.0"
}

processResources {
    inputs.property "version", project.version

    filesMatching("plugin.yml") {
        expand(version: project.version)
    }
}

jar {
    enabled = false
}

shadowJar {
    archiveClassifier = ""
    relocate "org.bstats", "net.nakedandafraid.paper.libs.bstats"
}

assemble {
    dependsOn shadowJar
}
